jobs:

- job:
  displayName: 'Windows 2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - script: |
      call activate myEnvironment
      conda install --yes --quiet --name myEnvironment -c conda-forge python=3.7 cmake
    displayName: Install Anaconda packages

  - script: |
      call activate myEnvironment
      python -m pip install -e Python
    displayName: Install Python library

  - script: cmake . -G "Visual Studio 15 2017 Win64" -Bcpp_build
    displayName: Run CMake generator

  - script: cmake --build cpp_build --config Release
    displayName: Build C++ library

  - script: cpp_build\Release\ExternalLibraryTest.exe
    displayName: Test C++ library

  - script: cmake . -G "Visual Studio 15 2017 Win64" -Bpython_build -DEXTERNAL_LANGUAGE=Python -DPYTHON_HOME=C:/Miniconda/envs/myEnvironment
    displayName: Run CMake generator

  - script: cmake --build python_build --config Release
    displayName: Build Python library

  - script: python_build\Release\ExternalLibraryTest.exe
    displayName: Test Python library
