[project]
name = "external-library"
version = "0.1.0"
description = "A Python library to be used in Modelica"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
