name: Build ExternalLibrary

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: cmake . -G "Visual Studio 17 2022" -Bcpp_build
    - run: cmake --build cpp_build --config Release
    - run: cpp_build\Release\ExternalLibraryTest.exe
    - run: $PYTHON_HOME = "${{ env.Python_ROOT_DIR }}" -replace "\\", "/"
    - run: echo "PYTHON_HOME=${{ PYTHON_HOME }}" | Out-File -FilePath $env:GITHUB_ENV -Append
    - run: echo "${{ env.PYTHON_HOME }}"
    - run: cmake . -G "Visual Studio 17 2022" -Bpython_build -DEXTERNAL_LANGUAGE=Python -DPYTHON_HOME="{{ env.PYTHON_HOME }}"
    - run: cmake --build python_build --config Release
    - run: python -m pip install -e Python
    - run: python_build\Release\ExternalLibraryTest.exe
